# Generated by Django 4.1.2 on 2022-10-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.IntegerField(verbose_name='شماره ی تماس')),
                ('message', models.TextField(verbose_name='پیام')),
                ('called_back', models.BooleanField(default=False, verbose_name='پاسخ داده شده یا خیر؟')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
            ],
        ),
    ]
